### ISSUE TITLE
Incorrect poe.ninja weapon prices

### ISSUE THREAD

**Issue by nmussy** [mtricht/lunaris#10]
![image](https://user-images.githubusercontent.com/2505696/72152722-1d77bf80-33ac-11ea-82a5-859ae001e592.png)

My guess is that the application fetches [all three results from poe.ninja](https://poe.ninja/challenge/unique-weapons?name=tremor), and selects the first one without checking the number of links.

**Comment by mtricht** [comment]
@nmussy thanks for reporting!  Fixed in commit above, will be release somewhere this weekend.
