### ISSUE TITLE
Hotkey customization

### ISSUE THREAD

**Issue by nevpo** [mtricht/lunaris#13]
Is there any way to change the default "alt+XYZ" hotkeys to some other combo (like "ctrl+XYZ" or something else)?
Thanks in advance.

**Comment by mtricht** [comment]
Currently not, but definitely something I will work on. Will use this issue to keep track of that.

**Comment by mtricht** [comment]
A config window is now in master, a screenshot: https://i.imgur.com/0jvE6dT.png
Will be released somewhere this week!
