### ISSUE TITLE
Alt+Q Item lookup uses incorrect type of mods

### ISSUE THREAD

**Issue by crusha015** [mtricht/lunaris#14]
When I use Alt+Q to pull up an item on pathofexile.com/trade, it often has incorrect mods attached so I get no results (even true with uniques).

Some examples of offending mods where the issue is quite prevalent is for any "local" mods.

The tool is entering the Explicit mod "Adds # to # Physical Damage". If I manually change this to use "Adds # to # Physical Damage (Local)" of the Pseudo "Adds # to # Physical Damage" it will work.

This is also true for mods with Increased Evasion, Armour, etc.

**Comment by gugg** [comment]
To pile on this, the sockets and link information are missing from the price estimator

**Comment by pvaass** [comment]
https://github.com/mtricht/lunaris/pull/45
