### ISSUE TITLE
Something is turning off my NumLock

### ISSUE THREAD

**Issue by crusha015** [mtricht/lunaris#15]
I haven't yet identified when exactly this is happening, but since I've started using this tool my NumLock is regularly being toggled off. I'll update the issue if I can get any better details, but I wanted to see if anyone else is experiencing this.

**Comment by mtricht** [comment]
@crusha015 I don't know man, that sounds really weird. We don't do anything with numlock anywhere in the code, are you sure it's not something else?

**Comment by crusha015** [comment]
Thanks for looking into it. It looks like you're right and it must be something else causing this. I guess I just coincidentally started to notice it after I installed Lunaris.

I just tested playing this morning without Lunaris even open and eventually my NumLock was toggled off.

**Comment by mtricht** [comment]
Closing this for now then, let me know if anything changes
