### ISSUE TITLE
Map scroll stuck bug

### ISSUE THREAD

**Issue by crusha015** [mtricht/lunaris#16]
I'm not sure if you already saw this one of the Reddit thread, but this post has a link to a clip of the issue in action: https://www.reddit.com/r/pathofexile/comments/emh24g/oops_we_are_also_working_on_a_trademacro_clone/fdpfcjl?utm_source=share&utm_medium=web2x

**Comment by mtricht** [comment]
@crusha015 thanks for linking, I have found the issue and fixed it in the commit above. Will be release soon!
