### ISSUE TITLE
Keybind Settings

### ISSUE THREAD

**Issue by BrockRiefenstahl** [mtricht/lunaris#17]
Hey there, will you add some functionality to change keybinds? I did not saw any config file where I could change them. For Example I need F2 for Hideout not F5 etc...

I just found out it does not work at all.

I am ingame now (Used the BAT file before. I see the icon in the tray (Options are POESSID / League / Exit.

But Ingame not even one of the Keybinds seem to work when hovered over items.

Playing on Windows 7

**Comment by mtricht** [comment]
@BrockRiefenstahl You're most likely running path of exile as administrator. If that's true, you also need to run the `.bat` file as administrator.

As for the customizable keybinds, that's currently not possible.

**Comment by BrockRiefenstahl** [comment]
That is not correct, I tested both, and neither method worked.

**Comment by pvaass** [comment]
Configuration UI merged in https://github.com/mtricht/lunaris/pull/29  adds configurable keybinds, closing issue.

**Comment by mtricht** [comment]
@BrockRiefenstahl would you mind trying out v0.4.0?
