### ISSUE TITLE
No results for some uniques 

### ISSUE THREAD

**Issue by alexaroth** [mtricht/lunaris#18]
![image](https://user-images.githubusercontent.com/1833388/72176213-d7375600-33d5-11ea-981e-728dd07efa11.png)

There are dozens of Ezomyte Peak Iron Hats on pathofexile trade but it can't find them for some reason

**Comment by alexaroth** [comment]
Ignore that, I realised its applying the attributes in the filter when searching, meaning I got a very rare values combination for the mods.

**Comment by mtricht** [comment]
@alexaroth until we're smarter about how we filter items, `alt + q` is your best friend!
