### ISSUE TITLE
F5 /hideout doesn't work with non-english keyboard layout

### ISSUE THREAD

**Issue by Kinsl** [mtricht/lunaris#21]
https://i.imgur.com/vpPlrPj.png
That's what I get when I press F5 while my keyboard layout is russian

**Comment by EThaNol2005** [comment]
can confirm: same with qwertz german layout.

**Comment by mtricht** [comment]
It seems that the library we use ([jnativehook](https://github.com/kwhat/jnativehook)) only supports QWERTY keyboards...will have to look for another solution to support different layouts.

**Comment by Kinsl** [comment]
It still writes /hideout but it's like I'm writing it myself with wrong layout

**Comment by berserkingyadis** [comment]
can confirm it not working also, on german keyboard

**Comment by mtricht** [comment]
@Kinsl @EThaNol2005 I have found a solution. I will be releasing an update tomorrow, after that it should work for all keyboard layouts! Verified by @berserkingyadis , thanks for testing again!
