### ISSUE TITLE
Add fast trade hotkey

### ISSUE THREAD

**Issue by Bannedmyself** [mtricht/lunaris#22]
Just like lutbot's a sequence of commands that would be
^{enter}{home}{delete}/invite {enter}

Ctrl+enter, picks up @player
home goes to char[0]
delete, deletes the @ and then writes "/invite " with a blank space

Thanks.

**Comment by mtricht** [comment]
@Bannedmyself thanks for the suggestions, added, will be in the release within 2 days!
