### ISSUE TITLE
Hotkeys do not work on equipped unusable items

### ISSUE THREAD

**Issue by ykz89** [mtricht/lunaris#23]
#### Steps to reproduce the issue
(Won't happen that often)
- Log on to character that has been transferred to standard/hardcore after the end of a league
or
- Level up gem to higher stat requirement than the character has

And use hotkeys on red equipped items.

#### What's the expected result?
- Hotkeys are functional

#### What's the actual result?
- Hotkeys have no effect

#### Additional details / screenshot
```
Rarity: Rare
You cannot use this item. Its stats will be ignored
--------
Beast Cloak
Sadist Garb
--------
Quality: +20% (augmented)
Evasion Rating: 594 (augmented)
Energy Shield: 122 (augmented)
--------
Requirements:
Level: 68
Dex: 103 (unmet)
Int: 109
--------
Sockets: B-B-B-G-G 
--------
Item Level: 76
--------
19% increased Evasion and Energy Shield
+63 to maximum Life
+61 to maximum Mana
+40% to Fire Resistance
+21% to Cold Resistance (crafted)
```

**Comment by mtricht** [comment]
@ykz89 thanks for reporting, fixed in commit linked above
