### ISSUE TITLE
Calculate Weapon DPS

### ISSUE THREAD

**Issue by berserkingyadis** [mtricht/lunaris#25]
If I remember correctly, poe trademacro had functionality to display the DPS numbers of weapons:

- physical dps
- ele/chaos dps
- total dps (phys + ele/chaos)

formula should be something like this: `(Minimum Damage + Maximum Damage) / 2 * Attacks per Second`

Those numbers could be added to the weapon tooltip or another display place of choice

**Comment by mtricht** [comment]
@berserkingyadis Thanks for the PR again! Is there anything you'd like to add to the weapon DPS or can we close this issue?

**Comment by berserkingyadis** [comment]
I think we can close this until there are more requirements.

**Comment by berserkingyadis** [comment]
One thing to do would be adding a DPS Preview to the Readme.md since there is not visibility for this feature yet. I sadly missed the 0.5 release so people wont know its in lunaris unless they see it somewhere.

**Comment by berserkingyadis** [comment]
added PR for it in https://github.com/mtricht/lunaris/pull/61

Link broken until its in main repo since link points to it
