### ISSUE TITLE
Search for Vaal skill gems show results for normal version

### ISSUE THREAD

**Issue by coldcode69** [mtricht/lunaris#27]
It doesn't seem to know about vaal gems or detect the vaal attribute properly. It just returns results as if you searched the normal version of the skill gem.

Also the poe.ninja price is based on the gem being 20% quality, regardless of the gems actual quality.

**Comment by mtricht** [comment]
@coldcode69 Thanks for reporting. I have added support for vaal gems which will be included in an update later this week.

As for the poe.ninja prices, poe.ninja does not have price information for all level/quality combinations. We try to match the closest possible quality/gem combination which is also displayed below the price: https://i.imgur.com/Ft6A7mk.png
