### ISSUE TITLE
Talisman price check does not work

### ISSUE THREAD

**Issue by Traf27** [mtricht/lunaris#31]
Price checks for talismans does not work. There is no popup. I'm on Win 7 64bit. 64bit client version, if that's matters.

Wierd because I saw in sourcefiles that there is pattern matching for Talisman keyword, and for amulets popup and price check works. 
I dont know if i can add anything else about bug.
Thanks!

**Comment by pvaass** [comment]
Fixed on master, will be solved in next release!
