### ISSUE TITLE
Can't use MercuryTrade with Lunaris running

### ISSUE THREAD

**Issue by zymox** [mtricht/lunaris#32]
While Lunaris and MercuryTrade are both running, whenever I press something that does a chat command on the MercuryTrade overlay (which is basically everything), it doesn't  work. It looks like the chat box opens and then immediately closes again, without typing anything.

**Comment by mtricht** [comment]
@zymox Thanks for letting us know, the latest release does indeed not work with MercuryTrade. However, the master branch does work with Mercury! So this will be fixed in the next release coming either tomorrow or thursday.
