### ISSUE TITLE
Nothing happens for "String Of Servitude" unique

### ISSUE THREAD

**Issue by coldcode69** [mtricht/lunaris#38]
Price check/open in browser doesn't do anything for this item. I have 3 with different implicit mods and none of them work.

https://www.pathofexile.com/trade/search/Metamorph/0n530QUg

**Comment by pvaass** [comment]
Created a branch here https://github.com/mtricht/lunaris/compare/feat/implicits that should fix your issue. However now all item implicits also get included in the search which might not be something everyone would want. Have to think of a smart way to handle this before release.
