### ISSUE TITLE
Preserve Clipboard after commands

### ISSUE THREAD

**Issue by berserkingyadis** [mtricht/lunaris#46]
After doing a few commands the Windows (and Linux?) Clipboard will hold the latest item data and the Clipboard state at the Start of the Program will be lost.

In the rare case that the User of the program is holding something important in the Clipboard it should be put into the Clipboard again after each command.

Also this may interfere with the copy pasted texts from the Poe trade sites.

Dont know how relevant this is, feedback is appretiated.

PS: to clarify:

User has Bank Account Password in Clipboard
User presses ALT-D to pricecheck their Item
   Lunaris backs up Clipboard
   Lunaris puts Item data in Clipboard
   Lunaris does its work
   Lunaris puts Bank Account Password back in Clipboard
User can still login to their Bank Site

**Comment by pvaass** [comment]
Hey Bers, thanks for creating an issue.

We're having some issues in general with the clipboard atm. (for instance, it logs everything you copy to your clipboard even without POE open).

Accessing the clipboard in Java is super sketchy, and randomly a lot of weird behaviour shows up. We can try to put the data back in the clipboard, but do note that this means that your (maybe sensitive) information at some point ends up saved as a variable in the JVM. Also there's just a (seemingly random) chance that the operating system will just flat out refuse to let us modify the clipboard.

I think if you order the codebase in amount of commits on the files, the code handling clipboard changes shows up on top :(

Anyway, we'll try to fix this (and other clipboard issues) asap.
