### ISSUE TITLE
Windows can't find javaw.exe

### ISSUE THREAD

**Issue by Megumin** [mtricht/lunaris#55]
Getting this error, don't know why. Have java installed already for games that may need such as Minecraft which works fine.

![yptLSVV](https://user-images.githubusercontent.com/40709124/73124737-6ec3a980-3f7d-11ea-951b-8c25030f8290.png)

**Comment by mtricht** [comment]
You downloaded the wrong zip file. See the README. Here's a direct link: https://github.com/mtricht/lunaris/releases/download/v0.5.1/lunaris-0.5.1-win64.zip
