### ISSUE TITLE
Windows cannot find javaw.exe

### ISSUE THREAD

**Issue by swaw3452** [mtricht/lunaris#65]
Whenever I try to start the macro, the cmd opens, it says it can't find the java file, and it exits. I checked the Environment Variables and the path is correct, so I'm not sure what to do from here.

**Comment by mtricht** [comment]
@swaw3452 you probably downloaded the wrong file, can you try with this one: https://github.com/mtricht/lunaris/releases/download/v0.5.1/lunaris-0.5.1-win64.zip

**Comment by swaw3452** [comment]
You got it, my bad. Thank you!
