### ISSUE TITLE
Lunaris doesn't work?

### ISSUE THREAD

**Issue by BarnOwlet** [mtricht/lunaris#67]
To keep it short, Lunaris worked for a quite a while flawlessly and then yesterday I had an incident with it: I couldn't get it to work! It was open, but no features worked at all. It ended up fixing itself after about 5 minutes, I've no idea how.
But today it happened again when I got online, been trying to get it to work again for about 1 hour now. Tried reinstalling multiple times, also changed the POESESSID multiple times. Tried keeping only it and PoE open, didn't work either. No idea what the issue is, but figured I should throw it out here..

**Comment by BarnOwlet** [comment]
Still hasn't been fixed, unfortunately. Lunaris doesn't work for a friend of mine either, so it can't be only us experiencing this issue..

**Comment by mtricht** [comment]
That's unfortunate and I haven't heard or seen such behavior myself.
What OS are you on? Keyboard language? Playing windowed/windowed fullscreen?

If you're willing to, could you open `lunaris.bat` in notepad and edit the contents to:

```
image\bin\java.exe -jar update4j.jar --remote https://raw.githubusercontent.com/mtricht/lunaris/master/autoupdater.xml --singleInstance
```

Do you see any error/exceptions when this happens?

**Comment by BarnOwlet** [comment]
Hey, thanks for answering.
We're both running Windows 7, with keyboard language on English, playing windowed fullscreen. I did try other keybinds, that didn't do the trick either.

I edited the thing you sent but the `log.txt` file is empty, 0 kb. I'm assuming that's because I reinstalled it and thus why there are no logs?
It's a real shame it randomly became unusable, I love the tool. If there's any more info you need to pinpoint the issue, I'd gladly help to see this sorted out.

**Comment by mtricht** [comment]
My bad, this should populate the logs.txt file with logs: `image\bin\java.exe  -Dorg.slf4j.simpleLogger.logFile=log.txt  -jar update4j.jar --remote https://raw.githubusercontent.com/mtricht/lunaris/master/autoupdater.xml --singleInstance`

It could be something windows 7 specific, I'll see if I can test that out in a VM.

**Comment by BarnOwlet** [comment]
Those are the only logs in the file now:
`18:59:25.409 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Saving explicit mods
18:59:25.410 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Saving fractured mods
18:59:25.411 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Saving crafted mods
18:59:25.412 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Getting leagues from pathofexile.com`

**Comment by BarnOwlet** [comment]
Had no luck finding the issue mate? :(

**Comment by mtricht** [comment]
There is nothing after `18:59:25.412 DEBUG dev.tricht.lunaris.com.pathofexile.PathOfExileAPI - Getting leagues from pathofexile.com`? Does the command prompt window stay open?

**Comment by BarnOwlet** [comment]
There's nothing. And the command prompt window stays open.

**Comment by BarnOwlet** [comment]
I finally fixed it by deleting the file with the tool's settings (the ones that remain even if you reinstall the tool). I have no clue why that would interfere with the tool functionality though.

**Comment by mtricht** [comment]
@BarnOwlet Do you happen to still have the 'corrupted' settings file you deleted?

**Comment by BarnOwlet** [comment]
Sorry, no >.> I'll make sure to let you know if it happens again though

**Comment by mtricht** [comment]
Please do!
