### ISSUE TITLE
Item Info not working

### ISSUE THREAD

**Issue by SoM6666** [mtricht/lunaris#68]
alt-c does not work at all, be it normal magic rare unique weapon.

**Comment by mtricht** [comment]
@SoM6666 What did you bind alt+c to? In the default config there is no alt+c

**Comment by SoM6666** [comment]
just re-downloaded lunaris and it's in the settings, look

**Comment by mtricht** [comment]
look where?

**Comment by SoM6666** [comment]
attached jpeg of lunaris settings

**Comment by SoM6666** [comment]
![lunseting](https://user-images.githubusercontent.com/61603710/75734272-80f3de80-5cc5-11ea-8890-b79c2e819e22.JPG)

**Comment by mtricht** [comment]
Ah, currently alt+c only works for maps. The screenshot for weapon DPS hasn't been released yet, it'll be included in a release I'll be doing this weekend to prepare for the upcoming patch.
