### ISSUE TITLE
Popup window: Couldn't talk with pathofexile.com

### ISSUE THREAD

**Issue by VyersReaver** [mtricht/lunaris#71]
Hey, yesterday the macro was working fine, now I can't launch it, says it "Couldn't talk with pathofexile.com, perhaps down for maintenance?"

Trade website and the forum for PoE work fine, any ideas on what it may be?

**Comment by mtricht** [comment]
@VyersReaver While the website and forums are up, everything is incredible slow. I managed to start lunaris on my third try, but it's basically unusable because the trade is also slow...not sure what we can do.

**Comment by VyersReaver** [comment]
Thanks for the reply! It's on the website side of things then. It's very slow now indeed.

**Comment by mtricht** [comment]
Seems to be more stable now, closing
