### ISSUE TITLE
Item search does not search on item category

### ISSUE THREAD

**Issue by superness** [mtricht/lunaris#74]
When using Alt+D or Alt+Q the search does not filter on item category.

For example this shield shows armors in the search results when I use Alt+Q. It also lists them in Alt+D but you would not know from the text displayed.

This is the search opened with Alt+Q: https://www.pathofexile.com/trade/search/Delirium/kW8ZWnwh5

Screenshots:
![shieldsearchexample](https://user-images.githubusercontent.com/6132089/79702254-58657b00-8258-11ea-8a5c-241d02b62d18.PNG)

![filtersexample](https://user-images.githubusercontent.com/6132089/79702257-5dc2c580-8258-11ea-8b0a-c2d2e2b4d91e.PNG)

![searchresultsexample](https://user-images.githubusercontent.com/6132089/79702258-60251f80-8258-11ea-8416-f063beb185f6.PNG)

**Comment by mtricht** [comment]
Will be fixed in the next release, thanks for reporting

**Comment by superness** [comment]
Confirmed fixed. Thanks!
