### ISSUE TITLE
Add Vulkan support

### ISSUE THREAD

**Issue by eduardo-bueno-ifood** [mtricht/lunaris#78]
It would be lovely to have it before the beginning of Harvest league, but I know it is unfeasible unless it is a very straightforward fix. I have zero JavaFX knowledge, but I can aid in any research or Java either.

**Comment by pvaass** [comment]
Duuude, nice coincidence. Check what I made yesterday: https://github.com/mtricht/lunaris/pull/77

We'll try to setup a new release tomorrow!

**Comment by mtricht** [comment]
@eduardo-bueno-ifood Released v0.6.0, see readme: https://github.com/mtricht/lunaris#faq

**Comment by eduardo-bueno-ifood** [comment]
You guys rock. Thanks so much for that!

**Comment by eduardo-bueno-ifood** [comment]
Just a heads up that with nVidia 451.48 driver and GPU scheduling on, this workaround is no longer necessary. it works just fine.
