### ISSUE TITLE
The currency stack pricer fails to identify chaos value on stack sizes greater than 999.

### ISSUE THREAD

**Issue by BrianCatan** [mtricht/lunaris#8]
Steps taken to identify issue:

1. Viewing a currency tab, hover over a common currency type that you have greater than 1000 items of and press alt+a. The price window fails to display.
2. Remove currency until stack size is <= 999 and press alt+a. The price window appears as expected.

I haven't confirmed with anyone else that this is happening, but it seems suspicious that every currency I have in quantity loses the alt+a functionality at exactly the first four digit number. If this is intended and not a bug, it might be a good idea to extend stack support out to 5000 since that's the max stack size in the currency tab. Fantastic work on the app in any case!

**Comment by ABortoc** [comment]
Can confirm, doesn't work for me on big stacks either.

**Comment by mtricht** [comment]
@BrianCatan @ABortoc Thanks for reporting, this has been fixed in v0.3.3 with the commit linked above.
