### ISSUE TITLE
Couldn't talk with pathofexile.com perhaps down for maintenance?

### ISSUE THREAD

**Issue by Duskhorizon** [mtricht/lunaris#86]
Getting this error all the time, website is working for me so is game : 
```
Pinging pathofexile.com [104.19.185.16] with 32 bytes of data:
Reply from 104.19.185.16: bytes=32 time=90ms TTL=49
Reply from 104.19.185.16: bytes=32 time=86ms TTL=49
Reply from 104.19.185.16: bytes=32 time=82ms TTL=49
Reply from 104.19.185.16: bytes=32 time=83ms TTL=49
```
any idea how i can diagnose this further?

**Comment by mtricht** [comment]
@Duskhorizon Are you able to open:
http://api.pathofexile.com/leagues

**Comment by Duskhorizon** [comment]
Yes , both links are working fine

**Comment by mtricht** [comment]
@Duskhorizon All right, open `lunaris.bat` with notepad and replace the contents with:

```
image\bin\java.exe -jar app\lunaris.jar
```

Save, run and can you then post the output?

**Comment by Duskhorizon** [comment]
It did run, output here :

https://pastebin.com/PND55WVE

but when i trying to do a price check i'm getting :

![obraz](https://user-images.githubusercontent.com/38585402/85335333-246b3800-b4dd-11ea-8caf-05369d90a23c.png)
