### ISSUE TITLE
Vulkan fix not working when Lunaris is opened before PoE

### ISSUE THREAD

**Issue by TheJamma** [mtricht/lunaris#87]
Everytime I open path of exile with lunaris already open i have to go to lunaris settings and untick the box and then tick it again for the fix to work.

**Comment by eduardo-bueno-ifood** [comment]
Try un-maximizing and then maximizing the game window. You can do it with the Alt + Space shortcut.

**Comment by mtricht** [comment]
Vulkan fix seems to be no longer needed
