### ISSUE TITLE
ctrl + scroll for stash not working

### ISSUE THREAD

**Issue by BarnOwlet** [mtricht/lunaris#88]
As the title suggests. Everything else is working as intended

Not sure what the problem is, I'm sure there's an easy fix but I can't find it..

**Comment by mtricht** [comment]
@BarnOwlet Is the setting enabled?
![image](https://user-images.githubusercontent.com/7511094/94344330-cdff1f80-001e-11eb-9601-03ff2f5c3cc5.png)

**Comment by BarnOwlet** [comment]
Right, now I have a different problem... For some reason, my PC just refused this entire day to let me open lunaris at all. Every time I launch it (as administrator aswell), it just gives me this:
![image](https://user-images.githubusercontent.com/60470422/94378582-8792e900-0122-11eb-844d-6a24c10ab02b.png)

I have no idea what's causing this either, lol.
As for the ctrl+scroll thing... I don't actually know if that was enabled in the settings, as I didn't mess with the keybinds tab. If it's not enabled by default though, then that must have been it, as I changed my PC and so the settings got resetted

**Comment by mtricht** [comment]
@BarnOwlet That's rather weird, did you try redownloading it? Direct link: https://github.com/mtricht/lunaris/releases/download/v0.6.3/lunaris-0.6.3-win64.zip

**Comment by BarnOwlet** [comment]
Yeah, I did. Multiple times over. Even deleted the settings file, which is placed rather differently from the main files of Lunaris.

**Comment by pvaass** [comment]
I've tried copying your file path in case that was the problem, but everything seems to work fine:
![image](https://user-images.githubusercontent.com/7511120/94492885-96919e00-01eb-11eb-8356-be7baeba6004.png)

I know this sounds stupid, but can you try following the steps @ https://support.microsoft.com/en-us/help/2669244/windows-cannot-access-the-specified-device-path-or-file-error-when-you

**Comment by BarnOwlet** [comment]
I have no idea what's going on anymore... lol

I tried opening it now, and it just worked. It just did, lol. It didn't work after a restart when I was trying to fix it a few days ago, so it couldn't have been that the PC just needed a restart.

It wasn't stupid at all for you to suggest the steps in that link @pvaass , but I stumbled upon that link when I was looking for a fix myself and did everything there, and they didn't work anyways. It was quite the haul aswell to look for a solution, because with the new laptop I switched from windows 7 to windows 10 and also changed my antivirus to Bitdefender, so everything's new...

Whatever... lol. I just hope that error won't come back. Oh, and you should know that the ctrl + scroll wasn't activated in the settings. So that was just me being very dumb and assuming it was just built into the tool, not that you have to turn it on. I swear to god though, you guys should make it activated by default when installed, to avoid another clown fiesta like this haha
