### ISSUE TITLE
Customize mod warnings

### ISSUE THREAD

**Issue by Yuyu** [mtricht/lunaris#9]
From what I see, *dangerous* mods are hardcoded inside `MapInfoListener`.
There should be a way to customize them, as different mods are considered dangerous for different builds (I can't run no mana regen maps, for example).

**Comment by mtricht** [comment]
This will be absolutely necessary. Keeping this issue to keep track of that!

**Comment by mtricht** [comment]
A config window is now in master with your requested mod, a screenshot: 
https://i.imgur.com/zSw1lIn.png
Will be released somewhere this week!
