### ISSUE TITLE
lunaris ddos trade sites

### ISSUE THREAD

**Issue by DarkStas** [mtricht/lunaris#93]
Please make some ddos protection for poe trade sites cos some of commands don't have delay between sending commands, like using "Search on /trade" hot key and it spam them.
And the question is why does it even send somewhere, some commands when I just try to open a link to the trade site (hot key  "Search on /trade").

**Comment by mtricht** [comment]
Use the POESESSID in settings.

When opening the item, we have to request the search as we get an ID back for that specific search.
